# SPDX-License-Identifier: Apache-2.0
"""Token-plan based draft proposer for Config C Sand-FSM.

The proposer is intentionally conservative: it only drafts deterministic
segments from the request token_plan. Natural-language model spans are always
generated by the target model.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping, Sequence


DETERMINISTIC_KINDS = frozenset({"fixed", "program", "choice", "score"})


@dataclass(frozen=True)
class FsmSpanDraftSegment:
    kind: str
    token_ids: tuple[int, ...] = ()
    json_path: str = ""

    @property
    def is_deterministic(self) -> bool:
        return self.kind in DETERMINISTIC_KINDS


class FsmSpanDraftState:
    """Tracks progress through an encoded token_plan and proposes fixed spans."""

    def __init__(self, segments: Sequence[FsmSpanDraftSegment]):
        self.segments = tuple(segments)
        self.segment_index = 0
        self.segment_offset = 0
        self.model_match_offset = 0
        self.completed = False
        self.disabled_reason: str | None = None
        self.observed_token_count = 0
        self.drafted_token_count = 0
        self.accepted_draft_token_count = 0
        self.fallback_count = 0
        self.forced_token_count = 0
        self.force_fallback_count = 0
        self.pending_draft_token_ids: list[int] = []

        self._advance_completed_segments()

    @classmethod
    def from_state(cls, state: Mapping[str, Any] | None) -> "FsmSpanDraftState | None":
        if not isinstance(state, Mapping):
            return None
        return cls.from_token_plan(state.get("token_plan"))

    @classmethod
    def from_token_plan(cls, token_plan: Any) -> "FsmSpanDraftState | None":
        if not isinstance(token_plan, Sequence) or isinstance(token_plan, str):
            return None

        segments: list[FsmSpanDraftSegment] = []
        for raw_segment in token_plan:
            if not isinstance(raw_segment, Mapping):
                return None
            kind = str(raw_segment.get("kind") or "")
            if kind == "model_span":
                segments.append(
                    FsmSpanDraftSegment(
                        kind=kind,
                        json_path=str(raw_segment.get("json_path") or ""),
                    )
                )
                continue
            if kind not in DETERMINISTIC_KINDS:
                return None
            token_ids = _normalize_token_ids(raw_segment.get("token_ids"))
            if not token_ids:
                return None
            segments.append(
                FsmSpanDraftSegment(
                    kind=kind,
                    token_ids=tuple(token_ids),
                    json_path=str(raw_segment.get("json_path") or ""),
                )
            )

        if not segments:
            return None
        return cls(segments)

    def disable(self, reason: str) -> None:
        if self.disabled_reason is None:
            self.fallback_count += 1
        self.disabled_reason = reason

    def observe_token_ids(self, token_ids: Sequence[int]) -> None:
        for raw_token_id in token_ids:
            if self.disabled_reason is not None or self.completed:
                return
            token_id = int(raw_token_id)
            self.observed_token_count += 1
            self._observe_draft_acceptance(token_id)
            self._observe_one(token_id)

    def propose(self, max_tokens: int) -> list[int]:
        if max_tokens <= 0 or self.disabled_reason is not None or self.completed:
            return []
        if self.pending_draft_token_ids:
            self.fallback_count += 1
            self.pending_draft_token_ids.clear()

        proposed = self.peek_deterministic(max_tokens)
        self.drafted_token_count += len(proposed)
        self.pending_draft_token_ids = list(proposed)
        return proposed

    def peek_deterministic(self, max_tokens: int) -> list[int]:
        if max_tokens <= 0 or self.disabled_reason is not None or self.completed:
            return []

        proposed: list[int] = []
        segment_index = self.segment_index
        segment_offset = self.segment_offset

        while len(proposed) < max_tokens and segment_index < len(self.segments):
            segment = self.segments[segment_index]
            if not segment.is_deterministic:
                break
            remaining = segment.token_ids[segment_offset:]
            if remaining:
                take = min(max_tokens - len(proposed), len(remaining))
                proposed.extend(remaining[:take])
                if len(proposed) >= max_tokens:
                    break
            segment_index += 1
            segment_offset = 0

        return proposed

    def commit_forced_token_ids(self, token_ids: Sequence[int]) -> list[int]:
        forced = [int(token_id) for token_id in token_ids]
        if not forced:
            return []
        if self.disabled_reason is not None or self.completed:
            return []

        expected = self.peek_deterministic(len(forced))
        if forced != expected:
            self.force_fallback_count += 1
            self.disable("forced deterministic token mismatch")
            return []

        self.forced_token_count += len(forced)
        self.observe_token_ids(forced)
        return forced

    def metrics(self) -> dict[str, Any]:
        acceptance_rate = (
            self.accepted_draft_token_count / self.drafted_token_count
            if self.drafted_token_count
            else 0.0
        )
        return {
            "fsm_enabled": True,
            "fsm_draft_tokens": self.drafted_token_count,
            "fsm_proposed_tokens": self.drafted_token_count,
            "fsm_accepted_tokens": self.accepted_draft_token_count,
            "fsm_rejected_tokens": max(
                0, self.drafted_token_count - self.accepted_draft_token_count
            ),
            "fsm_acceptance_rate": acceptance_rate,
            "fsm_fallback_count": self.fallback_count,
            "fsm_observed_tokens": self.observed_token_count,
            "fsm_forced_tokens": self.forced_token_count,
            "fsm_kv_advance_tokens": self.forced_token_count,
            "fsm_force_fallback_count": self.force_fallback_count,
            "fsm_completed": self.completed,
            "fsm_disabled": self.disabled_reason is not None,
            "fsm_disabled_reason": self.disabled_reason or "",
        }

    def _observe_draft_acceptance(self, token_id: int) -> None:
        if not self.pending_draft_token_ids:
            return
        expected = self.pending_draft_token_ids[0]
        if token_id == expected:
            self.accepted_draft_token_count += 1
            del self.pending_draft_token_ids[0]
            return
        self.fallback_count += 1
        self.pending_draft_token_ids.clear()

    def _observe_one(self, token_id: int) -> None:
        self._advance_completed_segments()
        if self.completed:
            return

        segment = self.segments[self.segment_index]
        if segment.is_deterministic:
            self._observe_deterministic(token_id, segment)
        else:
            self._observe_model_span(token_id)
        self._advance_completed_segments()

    def _observe_deterministic(
        self, token_id: int, segment: FsmSpanDraftSegment
    ) -> None:
        expected = segment.token_ids[self.segment_offset]
        if token_id != expected:
            self.disable(
                "deterministic token mismatch at segment "
                f"{self.segment_index} offset {self.segment_offset}"
            )
            return
        self.segment_offset += 1

    def _observe_model_span(self, token_id: int) -> None:
        next_index = self._next_deterministic_index(self.segment_index + 1)
        if next_index is None:
            return
        next_ids = self.segments[next_index].token_ids
        if not next_ids:
            return

        expected = next_ids[self.model_match_offset]
        if token_id == expected:
            self.model_match_offset += 1
            if self.model_match_offset == len(next_ids):
                self.segment_index = next_index
                self.segment_offset = len(next_ids)
                self.model_match_offset = 0
            return

        self.model_match_offset = 1 if token_id == next_ids[0] else 0

    def _advance_completed_segments(self) -> None:
        while self.segment_index < len(self.segments):
            segment = self.segments[self.segment_index]
            if not segment.is_deterministic:
                self.segment_offset = 0
                return
            if self.segment_offset < len(segment.token_ids):
                return
            self.segment_index += 1
            self.segment_offset = 0
            self.model_match_offset = 0
        self.completed = True

    def _next_deterministic_index(self, start_index: int) -> int | None:
        for index in range(start_index, len(self.segments)):
            if self.segments[index].is_deterministic:
                return index
        return None


def _normalize_token_ids(value: Any) -> list[int]:
    if not isinstance(value, Sequence) or isinstance(value, (str, bytes)):
        return []
    token_ids: list[int] = []
    for raw_token_id in value:
        if isinstance(raw_token_id, bool):
            return []
        try:
            token_ids.append(int(raw_token_id))
        except (TypeError, ValueError):
            return []
    return token_ids
